### ISSUE TITLE
Downloading Metadata Colour

### ISSUE THREAD

**Issue by lunarwolfspirit** [esskayesss/kanagawa-qbtheme#1] opened 2024-01-09 11:37 UTC
The colour when downloading metadata from magnet links looks nearly identical to the background - could we choose a different shade?

**Comment by esskayesss** [comment] 2024-01-09 16:58
i wanted to keep the downloading metadata colors pretty muted. you're correct in your observation, but it was intended at the time of making. i've made some changes, though. Brightened the `Downloading` and `Forced Downloading`. I've also changed the `Downloading Metadata` color.

please check the dev branch for the new theme. tell me if you like it. i'll merge it on a positive response. here's a link to the file: https://github.com/esskayesss/kanagawa-qbtheme/blob/dev/kanagawa.qbtheme

**Comment by lunarwolfspirit** [comment] 2024-01-09 22:58
Looks great now, thanks!

**Comment by esskayesss** [comment] 2024-01-10 08:14
merged ✅

**Closed as completed by esskayesss** 2024-01-10 08:14 UTC
